#!/bin/sh
./mkpngbutt bzoomin zoomin
./mkpngbutt bzoom zoom
./mkpngbutt bzoomout zoomout
./mkpngbutt bgzoom zoomin zoom zoomout

./mkpngbutt bundo undo
./mkpngbutt bredo redo
./mkpngbutt bgundo undo redo

./mkpngbutt bease enone
./mkpngbutt bgease enone

./mkpngbutt bgsnap snapcurs snapvis

./mkpngbutt bstraigh straight
./mkpngbutt bcurve curve1 openbutt
./mkpngbutt bcircle circle1 openbutt
./mkpngbutt bhelix helix
./mkpngbutt bturnout turnout
./mkpngbutt bhndldto hndldto
./mkpngbutt bturntbl turntbl
./mkpngbutt bparalle parallel
./mkpngbutt bgtrkcrt straight curve1 openbutt circle1 openbutt helix turnout hndldto turntbl parallel

./mkpngbutt bcurve1 curve1
./mkpngbutt bcurve2 curve2
./mkpngbutt bcurve3 curve3
./mkpngbutt bcurve4 curve4
./mkpngbutt bcircl1 circle1
./mkpngbutt bcircl2 circle2
./mkpngbutt bcircl3 circle3

./mkpngbutt bmodify extend
./mkpngbutt bjoin join
./mkpngbutt bconnect pull
./mkpngbutt bsplit splittrk
./mkpngbutt belev elev
./mkpngbutt bprofile profile
./mkpngbutt bmovedes movedesc
./mkpngbutt bgtrkmod extend join pull splittrk elev profile movedesc

./mkpngbutt bdescrib describe
./mkpngbutt bselect select
./mkpngbutt bgselect describe select

./mkpngbutt bmove move
./mkpngbutt brotate rotate
./mkpngbutt bflip flip
./mkpngbutt bdelete delete
./mkpngbutt btunnel tunnel
./mkpngbutt babove above
./mkpngbutt bbelow below
./mkpngbutt babvbel above below
./mkpngbutt bgtrkgrp move rotate flip delete tunnel above below

./mkpngbutt btext text
./mkpngbutt bdraw dline openbutt dcurve1 openbutt dcircle1 openbutt dbox openbutt
./mkpngbutt bnote cnote
./mkpngbutt bstruct struct
./mkpngbutt bgmsccrt text dline dcurve1 openbutt dcircle1 openbutt dbox openbutt cnote struct

./mkpngbutt dline dline
./mkpngbutt ddimlin ddimlin
./mkpngbutt dbench dbench
./mkpngbutt dtbledge dtbledge
./mkpngbutt dcurve1 dcurve1
./mkpngbutt dcurve2 dcurve2
./mkpngbutt dcurve3 dcurve3
./mkpngbutt dcurve4 dcurve4
./mkpngbutt dcircle2 dcircle2
./mkpngbutt dcircle3 dcircle3
./mkpngbutt dflcrcl2 dflcrcl2
./mkpngbutt dflcrcl3 dflcrcl3
./mkpngbutt dbox dbox
./mkpngbutt dfilbox dfilbox
./mkpngbutt dpoly dpoly
./mkpngbutt dfilpoly dfilpoly


./mkpngbutt bruler ruler
./mkpngbutt bgruler ruler

./mkpngbutt btrain train
./mkpngbutt bgtrain train
./mkpngbutt bnewcar newcar

exit 0
