#!/bin/sh

fetchdir() {
	echo fetching $1
	mkdir $1
	( cd $1; ln -s ../$2/src/$1/RCS . ; co -r$RLSE Makefile ; co -r$RLSE `make rcssrc` )
}

if [ $# -lt 1 ] ; then
	echo fetchall RLSE
	exit 1
fi
RLSE=$1
if [ -d ~/xtrkcad/$RLSE ] ; then
	echo ~/xtrkcad/$RLSE exists
	exit 1
fi
if [ -d ~/wlib/$RLSE ] ; then
	echo ~/wlib/$RLSE exists
	exit 1
fi

mkdir ~/xtrkcad/$RLSE
cd ~/xtrkcad/$RLSE
fetchdir bin ..
fetchdir help ..
fetchdir lib ..
fetchdir lib/demos ../..
fetchdir lib/examples ../..
fetchdir lib/params ../..
fetchdir tools ..
mkdir ~/wlib/$RLSE
cd ~/wlib/$RLSE
fetchdir include ..
fetchdir mswlib ..
fetchdir test ..
fetchdir gtklib ..

mkdir ~/xtrkcad/$RLSE/help/images.orig
cp ~/xtrkcad/dev/help/images.orig/*.png ~/xtrkcad/$RLSE/help/images.orig
cp ~/xtrkcad/dev/bin/xtrkcad.ico ~/xtrkcad/$RLSE/bin/
cp ~/xtrkcad/dev/lib/register.* ~/xtrkcad/$RLSE/lib/
chmod 444 ~/xtrkcad/$RLSE/lib/register.*
cp ~/wlib/dev/test/wtest.ico ~/wlib/$RLSE/test/
ln -s ~/wlib/$RLSE ~/xtrkcad/$RLSE/bin/wlib

