MISC=Makefile
SRCS=checkall diffall fetchall markall makeall mkrlse mkrlse.bat roall mkwinrlse

all: addcrlf src rcssrc


addcrlf: addcrlf.c
	$(CC) -g -o addcrlf addcrlf.c -lm
	
src:
	@echo $(MISC) $(SRCS)

rcssrc:
	@echo $(MISC) $(SRCS)
