#!/bin/sh

if [ $# -lt 1 ] ; then
	echo
	echo ERROR: Execute with $0 rel
	echo
	echo Example: $0 401
	echo where \<401\> is the release of XTrkCad to be packaged. 
	echo During execution of this script, the directory xtrkcad-\<rel\> is 
	echo created and all necessary files are collected into that directory.
	echo After that RPM is run to build the install package. After successful
	echo build, the files are deleted again.
	echo
	echo Execute from directory xtrkcad\\app
	echo
	exit 1
fi
RLSE=$1
DEST=xtrkcad-$RLSE

mkdir xtrkcad
mkdir xtrkcad/demos
mkdir xtrkcad/examples
mkdir xtrkcad/html
mkdir xtrkcad/html/png.d
mkdir xtrkcad/params


cp lib/xtrkcad.xtq xtrkcad/
cp lib/xtrkcad.bug xtrkcad/
cp lib/xtrkcad.enh xtrkcad/
cp lib/xtrkcad.fix xtrkcad/
cp lib/xtrkcad.upd xtrkcad/
cp lib/aareadme.txt xtrkcad/Readme.txt
cp lib/logo.bmp xtrkcad/logo.bmp
#cp help/xtrkcad.help xtrkcad/
cp help/xtrkcad.tip xtrkcad/
cp lib/examples/*.xtc xtrkcad/examples/
cp lib/params/*.xtp xtrkcad/params/
cp lib/demos/dm*.xtr xtrkcad/demos/
cp bin/xtrkcad xtrkcad/
cp bin/xtc64.xpm xtrkcad/
cp doc/*.html xtrkcad/html/
cp doc/xtrkcad_lin.css xtrkcad/html/
cp doc/png.d/*.png xtrkcad/html/png.d/
cp COPYING xtrkcad/
chmod 444 xtrkcad/*/*
chmod 444 xtrkcad/{Readme.txt,COPYING,xtc64.xpm,logo.bmp,xtrkcad.*}
chmod 777 xtrkcad/{demos,examples,html,params,html/png.d}
chmod 555 xtrkcad/xtrkcad
RLSE=`echo $RLSE | sed -e 's/r//' -e 's/_/./g'`
echo Building release $RLSE
tar cvfz  xtrkcad-linux-elf.${RLSE}.tar.gz xtrkcad 

D=`pwd`; # D=`dirname $D`; D=`basename $D`;
echo D = $D
V=`echo $RLSE | sed -e 's/^r//' -e 's/_/./g'`;
echo V = $V
sed -e "s#RLSEDIR#$D#g" -e "s#RLSEVER#$V#g"  lib/xtrkcad.spec.head > ./xtrkcad.spec

#find xtrkcad -type f -print | sed 's/^/\/usr\/local\/lib\//' | sed '/html/s/^/%doc /' | sed '/xtrkcad.help/s/^/%doc /'>> ./xtrkcad.spec
find xtrkcad -type f -print | sed 's/^/\/usr\/local\/lib\//' | sed '/html/s/^/%doc /' >> ./xtrkcad.spec

mkdir -p ./install/usr/local/lib
mv  ./xtrkcad ./install/usr/local/lib/xtrkcad
rpmbuild -bb xtrkcad.spec
mkdir $DEST
mv ./install/xtrkcad*\.rpm ./$DEST
mv ./xtrkcad-linux-elf.${RLSE}.tar.gz ./$DEST

rm -rf ./install
rm -f xtrkcad.spec
