#!/bin/sh
cd ~/xtrkcad/src
for d in bin help lib lib/params lib/demos lib/examples tools ; do
	rlog -R -L $d/RCS/*,v
done
cd ~/wlib/src
for d in include mswlib test gtklib ; do
	rlog -R -L $d/RCS/*,v
done

