#!/bin/sh

if [ $# -lt 1 ] ; then
	echo mkrlse RLSE
	exit 1
fi
RLSE=$1
if [ \! -d ~/xtrkcad/$RLSE ] ; then
	echo ~/xtrkcad/$RLSE does not exist
	exit 1
fi

	cd ~/wlib/$RLSE/gtklib && \
	make update  && \
	cd ~/xtrkcad/$RLSE/help && \
	make pngs && \
	make && \
	cd ../lib/params && \
	make && \
	cd .. && \
	make && \
	cd ../bin && \
	make update
