#!/bin/sh
if [ $# != 1 ] ; then
	echo "Usage: roall <RLSE>"
	exit 1
fi
cd ~/xtrkcad/$1
for d in bin help lib lib/params lib/demos lib/examples tools ; do
	(cd $d; for f in `make rcssrc` ; do
		if [ -w $f ] ; then
			echo $d/$f is writable
		fi
	done)
done
cd ~/wlib/$1
for d in include mswlib test gtklib ; do
	(cd $d;for f in `make rcssrc` ; do
		if [ -w $f ] ; then
			echo $d/$f is writable
		fi
	done)
done

